### ISSUE TITLE
Inefficient shifting within gen_cube

### ISSUE THREAD

**Issue by samuel-crypto** [pvial00/Cube#1]
In the `gen_cube` function what is essentially a rotation (putting the first member in the last place), described by this code:
```
int shift;
shift = alphabet.at(0);
alphabet.erase(alphabet.begin()+0);
alphabet.push_back(shift);
```
seems very inefficient - this is likely the reason for the slowness of this cipher (vs any complex operations), in implementations of ChaCha for instance use is made of the ultra-fast rotation `<<<` (which can be described in two C shifts with addition/subtraction and a gate), I would strongly suggest moving on a lower level (working with bytes, `uintX_t` types, the ultra fast binary and `<<` and `>>` operators, e.t.c.)

**Comment by pvial00** [comment]
gen_cube is quite fast and only used to generate the 3 dimenensional Cube state array.  The primary reason Cube is slow is due to the fact that the key is maintained as a 16 byte value that is changed in between encrypting bytes.  This and the swapping of those values through each Cube state (3 section x 3 alphabets per section = 9 alphabets total) is what makes Cube slow.  The design wasn't meant to be fast.

**Comment by samuel-crypto** [comment]
I will have a proper look, but a 16 byte value changed in between encrypting bytes seems like tiny compared to what other block ciphers keep between rounds

**Comment by pvial00** [comment]
There are 144 swap operations per round.  If you were to compare this with RC4 which has only one swap per round, Cube is incredibly slower.  In addition are 9 erase/push_back operations per round that happens in the encryption and decryption functions, that operation helps maintain uniformity. 
 Cube is a cipher machine that behaves like a modern stream cipher, originally designed to be implemented in hardware.
